### ISSUE TITLE
Discuss updating Eclipse version to work with BuildShip

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#106]
@jmdegeorge recommends moving to an updated version of Eclipse that comes built in with BuildShip. This ticket is created to track discussions with @hxiedwr before any action is done with updating the Eclipse version.

WRIMS v2.2 has framework that is dependent on the Eclipse Luna version. Unfortunately, with Eclipse Luna, There are issues with setting up BuildShip. 

@jmdegeorge please comment on the current version of the following:
- Eclipse Luna Version currently used for WRIMS v2.2
- Eclipse Version proposed to move to with BuildShip
- Java Version used for WRIMS v2.2

Part of this discussion should identify if we should move forward with updating the Eclipse version or if we should continue pursuing the effort to work with Eclipse Luna and BuildShip.

**Comment by dezidizon** [comment]
@hxiedwr - @jmdegeorge has invested about 17 hours on having Eclipse Luna work with BuildShip. Let us know if you'd like for us to continue pursuing this using Eclipse Luna, or consider updating to the recommended version.

**Comment by jmdegeorge** [comment]
Eclipse Luna Version currently used for WRIMS v2.2 = Eclipse LUNA (4.4.2)
Java Version used for WRIMS v2.2: Java 1.8.0.77

Suggest upgrading to Eclipse Photon (4.8) Which is the earliest reported version compatible with BuildShip v3.x
Photon is compatible with JDK 1.8 and would not require a java upgrade. 

Alternatively, consider migrating to the latest Eclipse, version 2024-06. 
However, Eclipse 2024-06 is built on Java v21.

**Comment by dezidizon** [comment]
Since the last discussion, the group has decided that the plugin automation will be moving forward with using the BND tool instead of Buildship. This discussion will now be closed.
