### ISSUE TITLE
dropins not always work

### ISSUE THREAD

**Issue by hxiedwr** [CentralValleyModeling/wrims#112]
Hi Peter and Tom, 
I am not sure if you plan to generate dropins and finish WRIMS2.2 auto build.
From my experience, most time dropins work with Eclipse Luna. But when you want to add a menu item or something on GUI, updating dropins is not good enough. The menu item or the added something just doesn't show up on GUI.
In those situations, what I did was: copy "config", "features", "plugins", and "P2" folders from Eclipse Luna to WRIMS GUI along with dropin update. Most time, it worked. But sometime, it wouldn't so I had to create a clone for the Eclipse Luna and made some minor modifications to convert it to WRIMS GUI.
So Eclipse has some mysterial behaviors. I don't know if RMA want to figure it out. If we don't understand what really happen, it is going to be hard to perform auto build on WIRMS 2.2. That is also a major concern for me to go with autobuild.

**Comment by adamkorynta** [comment]
Things identified in the meeting to try as a workaround
- see if bumping the version number between new versions of the plugin triggers a cache refresh
- have the updater script clean the cache of the WRIMS GUI prior to update-in-place

**Comment by hxiedwr** [comment]
I will create the code to add a new menu item and clear the cache in workspace of WRIMS 2 GUI to see if new menu item shows up.

If it fails, I will try to bump the plugin number.

I can do it on my computer with main branch. If both methods fails, I will share with RMA the code for menu added in.

Hao
________________________________

**Comment by hxiedwr** [comment]
My test showed clearing cache in workspace worked for adding menu item but not bouncing version number of dropin. The test files are in the attachment.
[test.zip](https://github.com/user-attachments/files/16966401/test.zip)

All the perspectives got closed out after cache is cleared. I will add Java code to load all the perspectives in.
