### ISSUE TITLE
Standard naming for new modules

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#117]
### Discussed in https://github.com/CentralValleyModeling/wrims/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **jmdegeorge** April 29, 2024</sup>
As the devops process moves forward, we'd like to make sure we standardize the naming of new modules at the top level.
Using the hyphen for naming conventions and short names for the module folders has been a common practice. 
I would like to suggest the following module folder names for the next modules in the queue for the DevOps updates:

\wrims-core (already complete)
\wrims-plugin     <= wrims_v2\wrimsv2_plugin
\dwr-hecdssvue  <= wrims_v2\gov.ca.dwr.hecdssvue
\dwr-jdiagram     <= wrims_v2\gov.ca.dwr.jdiagram

NOTE: The final output jar does not have to match the module folder name, but it is generally a good practice for it to do so. 

Thanks in advance for your feedback!
~Josh</div>

**Comment by hxiedwr** [comment]
As agreed with Josh, wrims-plugin will be changed to wrims.

Also I think we missed CalSimHydro plugin. Although it is not widely used, we want auto-build to keep all the components in manual build. I think this plugin is simple and easy to be built.

________________________________
From: dezidizon ***@***.***>
Sent: Tuesday, September 10, 2024 2:55 PM
To: CentralValleyModeling/wrims ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CentralValleyModeling/wrims] Standard naming for new modules (Issue #117)


Discussed in #99<https://github.com/CentralValleyModeling/wrims/discussions/99>

Originally posted by jmdegeorge April 29, 2024
As the devops process moves forward, we'd like to make sure we standardize the naming of new modules at the top level.
Using the hyphen for naming conventions and short names for the module folders has been a common practice.
I would like to suggest the following module folder names for the next modules in the queue for the DevOps updates:

\wrims-core (already complete)
\wrims-plugin <= wrims_v2\wrimsv2_plugin
\dwr-hecdssvue <= wrims_v2\gov.ca.dwr.hecdssvue
\dwr-jdiagram <= wrims_v2\gov.ca.dwr.jdiagram

NOTE: The final output jar does not have to match the module folder name, but it is generally a good practice for it to do so.

Thanks in advance for your feedback!
~Josh

**Comment by hxiedwr** [comment]
I think CalSimHydro is inside wrims plugin. No need to worry about CalSimHydro plugin.
________________________________

**Comment by jmdegeorge** [comment]
@hxiedwr, will it cause any issues for your testing the wrims-plugin jar if we rename it to wrims before the other parts of the application are updated to look for the "wrims" jar instead of "wrims-plugin" ?

**Comment by hxiedwr** [comment]
You can have the wrims plugin jar ready for me to test. We need have the ability to create plugin with a different name and make wrims gui work.
________________________________

**Comment by jmdegeorge** [comment]
I believe we are in agreement on the naming for all the modules: 

/wrims
/wrims-core
/third-party
/dwr-hecdssvue
/dwr-jdialog
/xtext
/xtext-ui

Tom and I ran into difficulties running the WRIMS gui with modified jar names, even after clearing the/workspace/.metadata folder. Will need to review process for picking up new/renamed jars with Hao (@hxiedwr )

Renaming the final dropin jars to match will be resolved under milestone 1.1.5 and tracked with the following issue:

https://github.com/CentralValleyModeling/wrims/issues/142

**Comment by hxiedwr** [comment]
I don't think this is the way to work. You can't rename all of them and complained renaming doesn't work.

What you probably need to do is keeping wrims_plugin, xtext, hecdssvue, jdialog as the orignial names and introducing 3rd-party plugin and test to see if this is the cause.

Once 3rd-party is confirmed that no problem is there, you can change the plugin name one by one and test. I think that is the only way to isolate the problems.

**Comment by jmdegeorge** [comment]
@hxiedwr I mostly agree with your approach to debugging the issue, my understanding for this particular ticket was to establish the naming of the module directories in the new gradle build structure. Would you like to keep this particular ticket open until we have established the correct process for running WRIMS with the wrimsv2_plugin_1.0.0.0 jar renamed to "wrims_1.0.0.0" ?

**Comment by hxiedwr** [comment]
I am fine what the approach you want to do. I mean you just don't know which plugins cause the problems you have as you renamed all of them together. You probably want to isolate the plugin you suspect, with old name and new name, to do the test.

wrimsv2_plugin plugin eventually have to be changed as WRIMS 3 is coming. If you can rename it from wrimsv2_plugin to wrims_plugin, to me, it can be renamed to any name. But anyway, WRIMS plugin is not the most critical. The most important is 3rd-party plugin works.

**Comment by hxiedwr** [comment]
By the way, I think "wrims_ide" is probably a better name than "wrims" for the plugin. The plugin mainly works for IDE and CalSimHydro. But people really don't use CalSimHydro through wrims gui. So I think "wrims_ide" should be good.

From: Xie, ***@***.***
Sent: Wednesday, October 9, 2024 12:57 PM
To: CentralValleyModeling/wrims ***@***.***>; CentralValleyModeling/wrims ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [CentralValleyModeling/wrims] Standard naming for new modules (Issue #117)

I am fine what the approach you want to do. I mean you just don't know which plugins cause the problems you have as you renamed all of them together. You probably want to isolate the plugin you suspect, with old name and new name, to do the test.

wrimsv2_plugin plugin eventually have to be changed as WRIMS 3 is coming. If you can rename it from wrimsv2_plugin to wrims_plugin, to me, it can be renamed to any name. But anyway, WRIMS plugin is not the most critical. The most important is 3rd-party plugin works.

**Comment by jmdegeorge** [comment]
@hxiedwr, I have identified a key location in the wrims2_gui\configuration\org.eclipse.equinox.simpleconfigurator\bundles.info file  where plugins must be registered. This where new modules like the third-party must be added and renamed modules must be updated for eclipse to launch them correctly. I have confirmed this process while renaming wrimsv2_plugin to "wrims-ide" as you suggested.
