### ISSUE TITLE
Build OSGI wrims-plugin module jar

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#118]
Build OSGI wrims-plugin module jar

**Comment by jmdegeorge** [comment]
OSGI jar is successfully building using the bnd gradle plugin. Eclipse jars for LUNA had to be added directly to the libs to satisfy compile as no working providers for the old LUNA jars could be established.

**Comment by jmdegeorge** [comment]
Code review have been completed and updates will be rolled forward into next milestones.
