### ISSUE TITLE
Build 3rd party OSGI bundle

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#121]
Build 3rd party OSGI bundle

**Comment by jmdegeorge** [comment]
Third-Party jar was successfully added as an additional module to a working WRIMS Gui. Third-party build design has been reviewed by Adam & Stephen with some improvements suggested. Will mark as complete once review comments and runtime dependencies have been resolved.

**Comment by jmdegeorge** [comment]
third party module is building and functioning as expected from developer testing. ready for testing from Hao to verify before closing issue.

**Comment by jmdegeorge** [comment]
All oustanding PR comments have been resolved. Merged into wrims-devops.
