### ISSUE TITLE
Build OSGI gov.ca.dwr.hecdssvue module jar

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#124]
Build OSGI gov.ca.dwr.hecdssvue module jar

**Comment by jmdegeorge** [comment]
hecdssvue module jar appears to be function as expected. ready for testing from Hao to verify before closing issue.

**Comment by jmdegeorge** [comment]
Code review comments have been addressed and ready for follow up from @adamkorynta & @stephen-rma

**Comment by hxiedwr** [comment]
I think plugins are interacted among each other. As RMA is testing individual plugin, I would suggest to have a full package for us when all the plugins are ready and then DWR will have some thorough tests.
________________________________

**Comment by jmdegeorge** [comment]
All code review comments have been resolved. Full testing of all the plugins together will be done through the final built installer.
