### ISSUE TITLE
Build OSGI gov.ca.dwr.wresl.xtext.editor.ui module jars

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#127]
Build OSGI gov.ca.dwr.wresl.xtext.editor.ui module jars

**Comment by jmdegeorge** [comment]
xtext-editor-ui jar is now building through gradle, need direction from @hxiedwr to smoke test their functionality.

**Comment by hxiedwr** [comment]
The test of xtext-editor includes 3 major parts I think:


  1.  Different keywords should have color
  2.  It can show error markers if WRESL code has error.
  3.  During debug, hoverring over a variable on the WRESL code, the value of the variable will be in the popup if that variable is used in the paused cycle and timestep.

**Comment by jmdegeorge** [comment]
Smoke tests have passed and xtext modules are building and included in devops release for DWR testing.
