### ISSUE TITLE
Build WRIMS plugins using gradle: Pull DWR dependencies from DWR GitHub Packages

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#13]

**Comment by jmdegeorge** [comment]
The wrims-core jar is being actively built and pulled into "wrims" through Gradle. 
@rma-tom or @hxiedwr , is there any other DWR dependencies that need to be pulled from DWR GitHub packages?

**Comment by hxiedwr** [comment]
I think this is the only one which has been actively revised. There was a CalSim.jar, which is stable and I think it is not used any more with HecLib 7. I think the diagram tool can check if this jar is depended.
________________________________

**Comment by jmdegeorge** [comment]
I confirmed in tattletale that the CalSim.jar is not required by wrims at this point.
