### ISSUE TITLE
Hao will follow-up on fix for the heclib 7 writing DSS 6 files

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#31]
Hao will follow-up on fix for the heclib 7 writing DSS 6 files.

**Comment by hxiedwr** [comment]
I tried with writing HecLib 6 format dss data by using HecLib 7, but never succeeded.

I need RMA to take a look at the code. WRIMS 2 has a flag to choose between HecLib 6 and HecLib 7 dss output.

Thank you,


Hao



________________________________
From: dezidizon ***@***.***>
Sent: Monday, December 18, 2023 3:32 PM
To: CVWRSM/wrims2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CVWRSM/wrims2] Hao will follow-up on fix for the heclib 7 writing DSS 6 files (Issue #31)


Hao will follow-up on fix for the heclib 7 writing DSS 6 files.

**Comment by adamkorynta** [comment]
Added gradle JavaExec task under PR: https://github.com/rmanet/cvwrsm/pull/7

**Comment by dezidizon** [comment]
This issue will now be closed. 
@hxiedwr has narrowed down the issue that is occurring with HecLib 7 generating HEC-DSS version 6 results. This is tracked in #44.
