### ISSUE TITLE
Create the new branch of CentralValleyModeling/wrims/feature/wrims-devops

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#41]
Create the new branch of CentralValleyModeling/wrims/feature/wrims-devops which includes the updates for the WRIMS DevOps effort.

Hao Xie approved the creation of this new branch during the meeting conducted on January 16, 2024.

This branch tracks @rma-tom 's effort in updating the directory structure for the wrims repository to work with gradle. 

Very strict control of how code is merged into this new branch will be implemented. No direct commits will be permitted. Commits must come through in peer approval. Conversations must be resolved before a pull request is merged into the wrims-devops branch.

A set of GitHub actions will be brought in to compose the jars and eventually assemble into wrims.

**Comment by rma-tom** [comment]
The branch is now created, and contains the first change we made, which was pushing the whole directory structure into a single folder named "wrims_v2". There's no actual development here yet.

**Comment by rma-tom** [comment]
Branch is created and builds a "wrims-core" jar when pushes or pull requests are made to CVM/Feature/wrims-devops.
