### ISSUE TITLE
Create unit test that exposes issue with DSS data being generated at the incorrect date and time

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#44]
With the current Hechlib version 7 generating HEC-DSS version 6 files, the data generated is saving the data at 24:00 instead of at 00:00. 

To investigate and address this issue, a unit test must be written exposing where the bad behavior occurs in the code. This can then be shared with Karl Tarbet and the development so that it can be addressed.

**Comment by hxiedwr** [comment]
[testHecLib7.zip](https://github.com/CentralValleyModeling/wrims/files/14232815/testHecLib7.zip)
I have some new findings:

when HecLib 7 output v6 format for monthly timestep, it stores the data at the 30 days after the first day of a month. For example, for Jan, it saves to Jan 30, for Feb, it saves to Mar 2, for Mar, it saves to Mar 30, for Apr, it saves to Apr 30... 

when HecLib 7 output v7 format for monthly timestep, the data is always saved at the end of a month, which is correct. For example, for Jan, it saves to Jan 31, for Feb, it saves to Feb 28, for Mar, it saves to Mar 31, for Apr, it saves to Apr 30...

Please see the attached zip file.

**Comment by dezidizon** [comment]
Steps forward:
- Determine the expected behavior to write the unit test for
- Write the unit test for the master branch
    - Create a branch off of the master branch
    - The unit test should pass in this new branch
    - Pull in updates into master branch
- Add written unit test to the Feature/HecDSS7 branch
    - This unit test should fail
    - The possible fix will be merged into this branch
 - This unit test will be shared with HEC to resolve the issue, as needed.
 - The unit test will be integrated into the Feature/wrims-devops branch so that future builds will verify that this issue no longer occurs.

**Comment by hxiedwr** [comment]
In order to have HecLib 7 to write data in 6 format, timestamp for the starting date of a timeseries has to end with 2400. For example, Oct 31, 1921 24:00. No other time can be used as the time stamp.

On the other hand, Java Calendar class consider 2400 to be the next day or time step. In the earlier example, Java Calendar will use it as Nov 1, 1921 00:00.

If there is no fix, WRIMS 2 have to back and forth between the 2 timestamps frequently in the code. They are off by 1 timestep in a monthly model.

**Comment by hxiedwr** [comment]
2400 Time stamp is only used when output dss data is required. In all other conditions, hour and minute time stamp is not used. Only year, month, and day are used in define time. The problem of writing data to dss file solved.
