### ISSUE TITLE
Set-up artifact repository to host artifacts and watersheds required for automated tests for WRIMS DevOps

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#53]
To establish automated testing for the WRIMS DevOps effort, an artifact repository needs to be established to host the watersheds and artifacts. The artifacts include the 3rd party jars and dlls that are bundled with CalSim and CalLite studies so that they can work at runtime.

@rma-tom will establish this artifact repository in GitHub Packages for now. This can be updated later on.

**Comment by rma-tom** [comment]
There are now GitHub packages associated with rmanet/cvwrsm. Libraries and a sample CalLite watershed have been uploaded and downloaded as artifacts for use in the comparison prototype (see #54)
