### ISSUE TITLE
Submit prototyping of comparison testing

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#54]
@rma-tom is in the process of prototyping the comparison testing on gradle. This work compares the results of running CalSim and CalLite studies using the wrims-core jar from Feature/wrims-devops against results from the current wrimsv2 jar.

**Comment by rma-tom** [comment]
A prototype of the comparison tool has been created in the Feature/comparison-test branch on rmanet/cwvrsm and a draft pull request has been created here. The prototype, at the time of this comment doesn't create a comparison report. That work will be covered under issue #56
