### ISSUE TITLE
Update the CalLite Report Tool to work with HecLib 7 and without the usage of Vista

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#61]
In #56, @hxiedwr recommended updating the CalLite Report Tool in WRIMS 2 to work with HecLib 7 without the usage of Vista.

**Comment by dezidizon** [comment]
During a meeting with @rma-tom, @rma-tom reported that he has successfully remove dependencies on the Vista libraries for the CalLite Report Tool. Updated the CalLite Report Tool to use HecLib 7 where needed.

Currently debugging executable to produce the same results as previous version of CalLite Report Tool. Goal is to produce the same results as previous in a PDF file.

**Comment by hxiedwr** [comment]
Could you share the link for the repository of CalLite Report Tool. I will find time to see if I can update the Report Tool in WRIMS 2 the same way.

**Comment by rma-tom** [comment]
I’ve still got some work to do before it can be shared.

  1.  The repository in the RMANET organization hasn’t been created yet.
  2.  The “debugging” needs to be completed. There are quite a few flaws in the computations. I’m optimistic that I’ll get through these quickly, because big ugly errors are usually easier to fix than subtle ones.

**Comment by hxiedwr** [comment]
Sounds good.
________________________________

**Comment by rma-tom** [comment]
The updated callite-report-tool is now in its own repo at [CentralValleyModeling](https://github.com/CentralValleyModeling/callite-report-tool)
It will make a report in the same format as the existing, Vista-based tool, but we need to verify that it correctly represents the model results. @hxiedwr -- do you have model results and a template that are suitable for testing/verification of the report tool?

**Comment by hxiedwr** [comment]
I will share a package for you later this afternoon.
________________________________

**Comment by hxiedwr** [comment]
DWR doesn't allow me to post link here to share files. I sent a separate email from sharepoint.

**Comment by dezidizon** [comment]
@rma-tom and myself have verified that the results from the updates to the CalLite Report Tool are as expected. @rma-tom has worked closely with @hxiedwr with discussing and verifying the results of the reports. Those comments are tracked in #76.

This item will now be closed.
