### ISSUE TITLE
Perform comparison testing over a longer simulation period to verify that small differences do not increase over time

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#66]
After the remaining issues with HecLib version 7 have been addressed, @hxiedwr tested the updates using DCR, DCP, and LTO CS3 studies producing DSS v6 and DSS v7 results.

@rma-tom recommended running the same tests using a longer simulation period to verify that small differences do not increase over time.

**Comment by hxiedwr** [comment]
The DCP study is from 1921 to 2021. The DCR and LTO studies are from 1921 to 2015. The longest CalSim 3 study is from 1921 to 2021. So we already tested the long period of study. If we want all the studies to be 1921 to 2021, we need have the latest changes from master branch to WRIMS-DevOps. But I think it is not necessary. The 3 studies we have run prove HecLib 7 works.

**Comment by dezidizon** [comment]
Per our discussion during the bi-weekly meeting on March 19, 2024, this ticket is considered done and will be closed.
