### ISSUE TITLE
Update CalLite Report Tool with updates incorporated with the EPPT updates

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#76]
Identify the updates done with the CalLite Report Tool in the context of EPPT. 

After the updates are identified, incorporate these updates in the standalone CalLite Report Tool.

**Comment by hxiedwr** [comment]
I updated the Report Tool in WRIMS GUI based on the updates of CalLite Report Tool to HecLib 7. I found a few issues:

1) The Report Tool could not import HecLib 7 format data. HecLib 6 format data works fine.
2) The cfs2taf function seems to have a problem. The summary table from the new Report Tool is different from the original Report Tool. Also I need help with developing similar taf2cfs function (To Do).
3) Need some instructions on how to build WRIMS-Core.jar and CalLite Report Tool. Hope to build the CalLite Report Tool and WRIMS-Core.jar to test with the HecLib 7 Dss files.

**Comment by dezidizon** [comment]
I created the following GitHub issues to track the issues @hxiedwr reported:

- The CalLite Report Tool could not import HecLib 7 format data [CalLite Report Tool issue #2](https://github.com/CentralValleyModeling/callite-report-tool/issues/2)
- Investigate the cfs2taf function in the CalLite Report Tool. [CalLite Report Tool issue #3](https://github.com/CentralValleyModeling/callite-report-tool/issues/3)
- Develop the taf2cfs function in the CalLite Report Tool. [CalLite Report Tool issue #4](https://github.com/CentralValleyModeling/callite-report-tool/issues/4)
- Provide instructions on how to build WRIMS-Core.jar and CalLite Report Tool #77.

The exchanges between @hxiedwr and @rma-tom have also been added to CalLite Report Issues 2 and 3.

**Comment by hxiedwr** [comment]
Tom has looked into the problems here and found:
1) report tool can use HecLib 7 dss data. Just the epart in the input file has to be "1Month" instead of "1MON".
2) cfs2taf function was implemented correct
3) Tom added taf2cfs function to wrims report tool
4) Tom drafted and provided me the instruction document to test auto build.

I suggest to close this issue.

**Comment by rma-tom** [comment]
Closing the issue in the CalLite report tool [#2 on that repo](https://github.com/CentralValleyModeling/callite-report-tool/issues/2) but leaving this one open until the keywords and other features from the WRIMS report are copied to the CalLite too.
