### ISSUE TITLE
Provide instructions on how to build WRIMS-Core.jar and CalLite Report Tool

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#77]
@hxiedwr requested instructions on building WRIMS-Core.jar and CalLite Report Tool. He is hoping to build the CalLite Report Tool and WRIMS-Core.jar to test with the HecLib 7 Dss files.

**Comment by hxiedwr** [comment]
Tom provided instruction document. I will test with it next week.

**Comment by rma-tom** [comment]
Provided instructions via email to @hxiedwr for importing callite-report-tool GitHub repo into an Eclipse project. Provided revised version of same to @dwr-ycheng following our meeting about devops tools see [here](https://github.com/CentralValleyModeling/callite-report-tool/issues/8)
