### ISSUE TITLE
Develop the taf2cfs function in the WRIMS 2 Report Tool

### ISSUE THREAD

**Issue by dezidizon** [CentralValleyModeling/wrims#78]
@hxiedwr requested in [wrims issue #76] for help in developing the taf2cfs function in the WRIMS 2 Report Tool.

**Comment by rma-tom** [comment]
New commit to branch reporttool [adding taf2cfs function](https://github.com/CentralValleyModeling/wrims/commit/8cb1ff019d1cfbe16b3cd93238c1fc56ad9ddf54) contains the new function.

**Comment by hxiedwr** [comment]
The function was added to the Report Tool of WRIMS GUI
